Rebase main branch during git-ship

diff --git a/git-ship b/git-ship
--- a/git-ship
+++ b/git-ship
@@ -23,6 +23,25 @@ function error_pull_feature_branch {
 }
 
 
+# Called by pull_feature_branch when the merge fails with conflicts
+function error_pull_main_branch {
+  echo_red "ERROR WHILE PULLING THE MAIN BRANCH"
+
+  # Create the abort file.
+  echo "git rebase --abort" > $abort_script
+  echo "git checkout $initial_branch_name" >> $abort_script
+  if [ $initial_open_changes == true ]; then
+    echo "git stash pop" >> $abort_script
+  fi
+
+  # Show error message.
+  echo "To undo this, run 'git ship --abort', or do the following steps manually:"
+  cat $abort_script
+  echo
+  exit 1
+}
+
+
 # Called when the squash merge of the feature branch fails with merge conflicts
 function error_squash_merge_feature_branch {
   echo_red "ERROR WHILE SQUASH-MERGING THE FEATURE BRANCH"
