git sync --abort

diff --git a/git-sync b/git-sync
--- a/git-sync
+++ b/git-sync
@@ -1,21 +1,92 @@
-#!/bin/bash -e
+#!/bin/bash
+
+# This file provides the "git sync" functionality.
+#
+# To handle errors, it defines a number of error handler methods.
+# These methods are called automatically by the respective git helper methods
+# when their operation fails.
+#
+# The error handlers create abort and continue scripts that are used when the
+# user runs "git sync --abort" and "git sync --continue".
+
+
 source "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/helpers/helpers.sh"
 
-echo_intro "SYNCING THE CURRENT BRANCH"
+# The path to the abort script
+abort_script="/tmp/git_sync_abort"
 
-stash_open_changes
-if [ "$current_branch_name" = "$main_branch_name" ]; then
-  # On the main branch
-  pull_main_branch
-  push_main_branch
+
+# Called by pull_feature_branch when the rebase fails with merge conflicts
+function error_pull_feature_branch {
+  echo_red "ERROR WHILE PULLING THE FEATURE BRANCH"
+
+  # Create the abort file.
+  echo "git rebase --abort" > $abort_script
+  if [ $has_open_changes == true ]; then
+    echo "git stash pop" >> $abort_script
+  fi
+
+  # Show error message.
+  echo "To undo this, run 'git sync --abort', or do the following steps manually:"
+  cat $abort_script
+  echo
+  exit 1
+}
+
+# Called by update_feature_branch when the rebase fails with merge conflicts
+function error_update_feature_branch {
+  echo_red "ERROR WHILE REBASING THE FEATURE BRANCH AGAINST THE MAIN BRANCH"
+
+  # Create the abort file.
+  echo "git rebase --abort" > $abort_script
+  if [ $has_open_changes == true ]; then
+    echo "git stash pop" >> $abort_script
+  fi
+
+  # Show error message.
+  echo "To undo this, run 'git sync --abort', or do the following steps manually:"
+  cat $abort_script
+  echo
+  exit 1
+}
+
+
+# Aborts a currently ongoing sync
+function abort_sync {
+  echo_intro "ABORTING THE PREVIOUS GIT SYNC"
+  if [ -f $abort_script ]; then
+    bash $abort_script
+    rm $abort_script
+    echo_all_done
+  else
+    echo_red "Cannot find abort definition file"
+  fi
+}
+
+
+# Perform the sync operation
+function perform_sync {
+  echo_intro "SYNCING THE CURRENT BRANCH"
+  stash_open_changes
+  if [ "$current_branch_name" = "$main_branch_name" ]; then
+    # On the main branch
+    pull_main_branch
+    push_main_branch
+  else
+    # On a feature branch
+    pull_feature_branch
+    pull_main_branch
+    update_feature_branch
+    push_feature_branch 'force'
+  fi
+  restore_open_changes
+  echo_all_done
+}
+
+
+if [ $1 == "--abort" ]; then
+  abort_sync
 else
-  # On a feature branch
-  pull_feature_branch
-  pull_main_branch
-  update_feature_branch
-  push_feature_branch 'force'
+  perform_sync
 fi
-restore_open_changes
-
-echo_all_done
 
