Rebase the main branch when updating it

diff --git a/git-extract b/git-extract
--- a/git-extract
+++ b/git-extract
@@ -27,6 +27,25 @@ function error_cherry_pick {
 }
 
 
+# Called by pull_feature_branch when the merge fails with conflicts
+function error_pull_main_branch {
+  echo_red "ERROR WHILE PULLING THE MAIN BRANCH"
+
+  # Create the abort file.
+  echo "git rebase --abort" > $abort_script
+  echo "git checkout $initial_branch_name" >> $abort_script
+  if [ $initial_open_changes == true ]; then
+    echo "git stash pop" >> $abort_script
+  fi
+
+  # Show error message.
+  echo "To undo this, run 'git extract --abort', or do the following steps manually:"
+  cat $abort_script
+  echo
+  exit 1
+}
+
+
 # Performs the extract operation
 function perform_extract {
   local target_branch_name=$1
diff --git a/git-sync b/git-sync
--- a/git-sync
+++ b/git-sync
@@ -46,6 +46,34 @@ function error_pull_feature_branch {
 }
 
 
+# Called by pull_feature_branch when the merge fails with conflicts
+function error_pull_main_branch {
+  echo_red "ERROR WHILE PULLING THE MAIN BRANCH"
+
+  # Create the abort file.
+  echo "git rebase --abort" > $abort_script
+  echo "git checkout $initial_branch_name" >> $abort_script
+  if [ $initial_open_changes == true ]; then
+    echo "git stash pop" >> $abort_script
+  fi
+
+  # Create the continue file.
+  echo "pull_main_branch" > $continue_script
+  echo "update_feature_branch" >> $continue_script
+  echo "push_feature_branch" >> $continue_script
+  if [ $initial_open_changes == true ]; then
+    echo "git stash pop" >> $continue_script
+  fi
+
+  # Show error message.
+  echo "To undo this, run 'git sync --abort', or do the following steps manually:"
+  cat $abort_script
+  echo "To continue after you have resolved the conflict, run 'git sync --continue'"
+  echo
+  exit 1
+}
+
+
 # Called by update_feature_branch when the merge fails with merge conflicts
 function error_update_feature_branch {
   echo_red "ERROR WHILE REBASING THE FEATURE BRANCH AGAINST THE MAIN BRANCH"
diff --git a/git-sync-fork b/git-sync-fork
--- a/git-sync-fork
+++ b/git-sync-fork
@@ -2,6 +2,43 @@
 
 source "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/helpers/helpers.sh"
 
+# The path to the abort script
+abort_script="/tmp/git_sync_fork_abort$temp_filename_suffix"
+
+
+
+# Aborts a currently ongoing sync-fork
+function abort_sync_fork {
+  echo_intro "ABORTING THE PREVIOUS GIT SYNC-FORK"
+  if [ -f $abort_script ]; then
+    source $abort_script
+    rm $abort_script
+    echo_all_done
+  else
+    echo_red "Cannot find abort definition file"
+  fi
+}
+
+
+# Called by pull_feature_branch when the merge fails with conflicts
+function error_pull_upstream_branch {
+  echo_red "ERROR WHILE PULLING THE UPSTREAM BRANCH"
+
+  # Create the abort file.
+  echo "git rebase --abort" > $abort_script
+  echo "git checkout $initial_branch_name" >> $abort_script
+  if [ $initial_open_changes == true ]; then
+    echo "git stash pop" >> $abort_script
+  fi
+
+  # Show error message.
+  echo "To undo this, run 'git sync-fork --abort', or do the following steps manually:"
+  cat $abort_script
+  echo
+  exit 1
+}
+
+
 # Outputs error and exits
 function error_with_upstream_required {
   echo_error_header
@@ -54,6 +91,8 @@ function sync_fork {
 if [ "$1" == "--configure-only" ]; then
   echo_intro "CONFIGURING REMOTE UPSTREAM"
   configure_upstream
+elif [ "$1" == "--abort" ]; then
+  abort_sync_fork
 else
   echo_intro "SYNCING THE MAIN BRANCH WITH REMOTE UPSTREAM"
   sync_fork
